version: 2.1

orbs:
  node: circleci/node@5.0.0

workflows:
  lint:
    jobs:
      - node/run:
          name: "lint"
          npm-run: lint
  matrix-tests:
    jobs:
      - node/run:
          name: "build"
          npm-run: build
          matrix:
            parameters:
              version:
                - "16.14"
                - "14.19"
      - node/test:
          name: "unit tests"
          matrix:
            parameters:
              version:
                - "16.14"
                - "14.19"
