---

version: 2.1

orbs:
  node: circleci/node@5.0.0

workflows:
  lint:
    jobs:
      - node/run:
          name: "lint"
          npm-run: lint
  matrix-tests:
    jobs:
      - node/test:
          name: "unit tests"
          matrix:
            parameters:
              version:
                - "18.9"
                - "16.17"
                - "14.20"
